services:
  balatro-completionist-plus-plus-tracker:
    container_name: balatro-completionist-plus-plus-tracker
    image: balatro-completionist-plus-plus-tracker:2.1.0
    build: .
    ports:
      - "8087:8080"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "-Y",
          "off",
          "http://127.0.0.1:8080/__miniserve_internal/healthcheck",
        ]
      interval: 5s
      timeout: 2s
      start_period: 10s
      retries: 3
